// Builds a standalone pzmap-bridge executable with the CLI baked in via
// Node's Single Executable Application feature. Nobody running the result
// needs Node.js or npm installed — the binary *is* the Node runtime, plus
// the bridge as a bundled CJS payload.
//
//   node sea/build.mjs                     builds for the machine you're on
//   node sea/build.mjs --target=linux-x64  cross-builds a Linux x64 binary
//                                          by downloading the matching
//                                          official Node release, verifying
//                                          its checksum, and injecting into
//                                          that instead of the local binary
//
// Cross-building works because postject only rewrites bytes in an existing
// binary — it never has to execute it. The downloaded Node build is pinned
// to the exact version running this script, since the SEA blob (built once,
// reused across targets — no snapshot/codeCache, so it's just bundled JS
// text) is generated by --experimental-sea-config against *this* Node.
// Structurally verified (ELF header, size) — not execution-verified; this
// environment has no Linux runtime to actually run the result on.
//
// Run: node sea/build.mjs [--target=linux-x64]   (after `npm run build`)

import { execFileSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdtempSync, rmSync, createWriteStream, readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { pipeline } from 'node:stream/promises';

const seaDir = dirname(fileURLToPath(import.meta.url));
const bridgeDir = dirname(seaDir);
const FUSE = 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2';
const NODE_VERSION = process.version; // e.g. "v24.19.0" — pinned to this script's own runtime

if (!existsSync(join(bridgeDir, 'dist', 'sea-entry.js'))) {
  console.error('dist/sea-entry.js not found — run `npm run build` first.');
  process.exit(1);
}

const targetArg = process.argv.find((a) => a.startsWith('--target='));
const target = targetArg ? targetArg.slice('--target='.length) : null;

if (target && target !== 'linux-x64') {
  console.error(`Unsupported --target=${target}. Only linux-x64 cross-builds are supported; omit --target to build natively.`);
  process.exit(1);
}

// `work` is created by the caller (and its cleanup registered) before this
// runs, so a throw here never leaves an untracked temp dir behind — the
// caller's finally block removes whatever was created regardless of where
// this fails.
async function downloadLinuxNodeBinary(work) {
  const archiveName = `node-${NODE_VERSION}-linux-x64.tar.xz`;
  const baseUrl = `https://nodejs.org/dist/${NODE_VERSION}`;

  console.log(`Fetching the official checksum list for ${NODE_VERSION}...`);
  const sumsRes = await fetch(`${baseUrl}/SHASUMS256.txt`);
  if (!sumsRes.ok) throw new Error(`Could not fetch SHASUMS256.txt (${sumsRes.status})`);
  const sums = await sumsRes.text();
  const match = sums.split('\n').find((line) => line.endsWith(archiveName));
  if (!match) throw new Error(`No checksum entry for ${archiveName}`);
  const expectedHash = match.split(/\s+/)[0];

  const archivePath = join(work, archiveName);

  console.log(`Downloading ${archiveName}...`);
  const res = await fetch(`${baseUrl}/${archiveName}`);
  if (!res.ok) throw new Error(`Could not download ${archiveName} (${res.status})`);
  await pipeline(res.body, createWriteStream(archivePath));

  console.log('Verifying checksum...');
  const actualHash = createHash('sha256').update(readFileSync(archivePath)).digest('hex');
  if (actualHash !== expectedHash) {
    throw new Error(`Checksum mismatch for ${archiveName}: expected ${expectedHash}, got ${actualHash}`);
  }
  console.log('Checksum verified.');

  console.log('Extracting...');
  // --force-local: Windows' bundled bsdtar otherwise misreads the "C:\..."
  // drive-letter colon in these paths as remote-host syntax ("host:path").
  execFileSync('tar', ['-xJf', archivePath, '-C', work, '--force-local']);
  const nodeBinary = join(work, `node-${NODE_VERSION}-linux-x64`, 'bin', 'node');
  if (!existsSync(nodeBinary)) throw new Error(`Extracted archive did not contain bin/node at the expected path`);

  return nodeBinary;
}

let cleanup = () => {};

try {
  console.log('Bundling to a single CJS file...');
  // shell: true is required on Windows to invoke npx (a .cmd file) at all —
  // safe here since every argument below is a static literal, never user input.
  execFileSync('npx', ['esbuild', 'dist/sea-entry.js', '--bundle', '--platform=node', '--format=cjs', '--outfile=sea/bundle.cjs'], {
    cwd: bridgeDir,
    stdio: 'inherit',
    shell: true,
  });

  console.log('Generating the SEA blob...');
  execFileSync(process.execPath, ['--experimental-sea-config', 'sea-config.json'], {
    cwd: seaDir,
    stdio: 'inherit',
  });

  let outName;

  if (target === 'linux-x64') {
    const work = mkdtempSync(join(tmpdir(), 'pzmap-bridge-linux-node-'));
    cleanup = () => rmSync(work, { recursive: true, force: true });
    const nodeBinary = await downloadLinuxNodeBinary(work);
    outName = 'pzmap-bridge-linux-x64';
    console.log('Copying the downloaded Linux Node binary...');
    copyFileSync(nodeBinary, join(seaDir, outName));
  } else {
    outName = process.platform === 'win32' ? 'pzmap-bridge.exe' : 'pzmap-bridge';
    console.log('Copying the local Node binary...');
    copyFileSync(process.execPath, join(seaDir, outName));
  }

  console.log('Injecting the blob (postject)...');
  execFileSync('npx', [
    'postject', `sea/${outName}`, 'NODE_SEA_BLOB', 'sea/sea-prep.blob',
    '--sentinel-fuse', FUSE,
  ], {
    cwd: bridgeDir,
    stdio: 'inherit',
    shell: true,
  });

  console.log(`\nDone: bridge/sea/${outName}`);
  if (outName.endsWith('.exe')) {
    console.log('It is unsigned — Windows SmartScreen may prompt on first run (More info -> Run anyway).');
  } else {
    console.log('Remember: chmod +x it before running on Linux (Windows/NTFS doesn\'t carry the executable bit).');
  }
} finally {
  cleanup();
}
